version: '3.8'

services:
  backend:
    build:
      context: ./backend-django/backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:

       - ./backend-django/backend:/app

    ports:
      - "8000:8000"
    env_file: .env 
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mydatabases3
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: White450602
    ports:
      - "5433:5432"   # ใช้ 5433 ภายนอกเครื่อง, 5432 ภายใน container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user1 -d mydatabases3"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork
volumes:
  postgres_data:
 


networks:
  mynetwork:

